'use client';

import React from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/Card';
import { FAQStructuredData } from '@/components/seo/StructuredData';

const faqs = [
  {
    question: 'How does the AI Cover Letter Generator work?',
    answer: 'Our AI Cover Letter Generator uses advanced artificial intelligence to analyze your job details, personal information, and target position. It then creates a personalized, professional cover letter that matches the job requirements and highlights your relevant skills and experience.',
  },
  {
    question: 'Are the cover letters ATS-optimized?',
    answer: 'Yes, all cover letters generated by our AI are optimized for Applicant Tracking Systems (ATS). We ensure proper formatting, keyword optimization, and structure that helps your application pass through ATS filters and reach human recruiters.',
  },
  {
    question: 'Can I customize the generated cover letters?',
    answer: 'Absolutely! Our AI Cover Letter Generator provides multiple professional templates and allows you to edit and customize every aspect of your cover letter. You can modify content, adjust formatting, and personalize the tone to match your style.',
  },
  {
    question: 'How long does it take to generate a cover letter?',
    answer: 'Our AI Cover Letter Generator creates professional cover letters in just minutes. Simply input your job details and personal information, select a template, and receive your customized cover letter instantly.',
  },
  {
    question: 'Is my personal information secure?',
    answer: 'Yes, we take data security seriously. All personal information and job details are encrypted and stored securely. We follow enterprise-grade security standards to protect your privacy and ensure your data is never shared with third parties.',
  },
  {
    question: 'Can I export my cover letters to PDF?',
    answer: 'Yes, you can easily export your AI-generated cover letters to PDF format with one click. The PDF maintains professional formatting and is ready for immediate submission to employers or printing.',
  },
];

const FAQItem = React.memo(({ faq, index }: { faq: typeof faqs[0]; index: number }) => (
  <Card className="animate-fade-in" style={{ animationDelay: `${index * 100}ms` }}>
    <CardHeader>
      <CardTitle className="text-lg">{faq.question}</CardTitle>
    </CardHeader>
    <CardContent>
      <p className="text-on-surface-variant leading-relaxed">{faq.answer}</p>
    </CardContent>
  </Card>
));

FAQItem.displayName = 'FAQItem';

export const FAQSection = React.memo(() => (
  <>
    <FAQStructuredData faqs={faqs} />
    <section className="py-20 sm:py-32">
      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <div className="mx-auto max-w-2xl text-center">
          <h2 className="text-on-surface text-3xl font-bold tracking-tight sm:text-4xl">
            Frequently Asked Questions
          </h2>
          <p className="text-on-surface-variant mt-4 text-lg leading-8">
            Everything you need to know about our AI Cover Letter Generator
          </p>
        </div>
        <div className="mx-auto mt-16 grid max-w-4xl grid-cols-1 gap-6 sm:mt-20 lg:grid-cols-2">
          {faqs.map((faq, index) => (
            <FAQItem key={faq.question} faq={faq} index={index} />
          ))}
        </div>
      </div>
    </section>
  </>
));

FAQSection.displayName = 'FAQSection';
